### ISSUE TITLE
Separator item

### ISSUE THREAD

**Issue by patarapolw** [rawilk/vue-context#77]
### Description

Separator item is missing from official. However, I can easily create it with CSS. Also works with CSS scoped.

```html
<vue-context>
  <li class="separator"><a></a></li>
</vue-context>
```

```scss
.v-context {
  li.separator {
    display: flex;
    flex-direction: row;
    justify-content: center;
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;

    a {
      background-color: lightgray;
      height: 1px;
      width: calc(100% - 1rem);
      padding: 0;
    }
  }
}
```

### Version

```
vue-context@6.0.0

Firefox for Ubuntu 84.0 on Xubuntu 20.04
```
